services:
  - type: web
    name: simulador-robotica-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 -b 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
